export const chatList = [
  {
    name: 'Валера',
    avatarUrl: 'https://i.ytimg.com/vi/In11LnTuLvg/maxresdefault.jpg',
    lastMessage: 'привет пока',
    id: '123',
    timeStamp: '19:20',
    counter: 5,
  },
  {
    name: 'Валера',
    avatarUrl: 'https://i.ytimg.com/vi/In11LnTuLvg/maxresdefault.jpg',
    lastMessage: 'привет пока',
    id: '123',
    timeStamp: '19:20',
    counter: 5,
  },
  {
    name: 'Валера',
    avatarUrl: 'https://i.ytimg.com/vi/In11LnTuLvg/maxresdefault.jpg',
    lastMessage: 'привет пока',
    id: '123',
    timeStamp: '19:20',
    counter: 5,
  },
  {
    name: 'Валера',
    avatarUrl: 'https://i.ytimg.com/vi/In11LnTuLvg/maxresdefault.jpg',
    lastMessage: 'привет пока',
    id: '123',
    timeStamp: '19:20',
    counter: 5,
  },
  {
    name: 'Валера',
    avatarUrl: 'https://i.ytimg.com/vi/In11LnTuLvg/maxresdefault.jpg',
    lastMessage: 'привет пока',
    id: '123',
    timeStamp: '19:20',
    counter: 5,
  },
  {
    name: 'Валера',
    avatarUrl: 'https://i.ytimg.com/vi/In11LnTuLvg/maxresdefault.jpg',
    lastMessage: 'привет пока',
    id: '123',
    timeStamp: '19:20',
    counter: 5,
  },
  {
    name: 'Валера',
    avatarUrl: 'https://i.ytimg.com/vi/In11LnTuLvg/maxresdefault.jpg',
    lastMessage: 'привет пока',
    id: '123',
    timeStamp: '19:20',
    counter: 5,
  },
  {
    name: 'Валера',
    avatarUrl: 'https://i.ytimg.com/vi/In11LnTuLvg/maxresdefault.jpg',
    lastMessage: 'привет пока',
    id: '123',
    timeStamp: '19:20',
    counter: 5,
  },
  {
    name: 'Валера',
    avatarUrl: 'https://i.ytimg.com/vi/In11LnTuLvg/maxresdefault.jpg',
    lastMessage: 'привет пока',
    id: '123',
    timeStamp: '19:20',
    counter: 5,
  },
];
